apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - port: 80
      name: nginx-port
      targetPort: 80
      nodePort: 30000
    - port: 8080
      name: multitool-port
      targetPort: 1180
      nodePort: 30001